services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    
    environment:
        - BASE_URL=http://backend:8000
        
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yion_user -d yion_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
