location = /visitors/track {
    limit_req zone=visitor_tracking burst=10 nodelay;
    limit_req_status 429;
    client_max_body_size 2k;
    proxy_pass http://backend-origin:8000;
}
location /docs { deny all; }
location / {
    proxy_pass http://backend-origin:8000;
}
